### ISSUE TITLE
no .csproj file in source

### ISSUE THREAD

**Issue by DoomsickIe** [Aceisbest/Promovements_Fixed#1]
how did you even manage to build this without it? (Its fixed)

**Comment by Aceisbest** [comment]
> how did you even manage to build this without it?

Magic

**Comment by prolificpain** [comment]
> how did you even manage to build this without it?

probably dnspy :p

**Comment by Aceisbest** [comment]
> > how did you even manage to build this without it?
> 
> probably dnspy :p

Uaa, 1. The code is on GitHub. 2. I asked if I could remake it ;p
